spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: hawkbit-mcp-server
            client-secret: 7518f687-51b9-41c7-b2c4-a87efb1a8c93
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://dev.mobitbrasil.com.br/auth/realms/mobit/protocol/openid-connect/token    

  application:
    name: hawkbit-mcp-server

  ai:
    mcp:
      server:
        name: hawkbit-mcp-server
        version: 0.0.1
        type: SYNC
        annotation-scanner:
          enabled: true
  main:
    web-application-type: NONE
    banner-mode: OFF

logging:
  level:
    root: OFF

hawkbit:
  server:
    mgmt-url: http://localhost:8080
    ddi-url: http://localhost:8085

server:
  port: 8090

        